In [1]:
import seaborn as sb
import polars as pl

In [2]:
df = pl.scan_csv("penalties_py_0.txt", separator="\t")

In [29]:
pos_df = df.filter(pl.col("Reaction").str.ends_with("_pos")).select(pl.col("Reaction").str.replace("_pos", ""), pl.selectors.numeric())
neg_df = df.filter(pl.col("Reaction").str.ends_with("_neg")).select(pl.col("Reaction").str.replace("_neg", ""), pl.selectors.numeric())

In [22]:
pos_df.head().collect()

shape: (5, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Reaction  ┆ WT-d_S141 ┆ Ob-DHA-e_ ┆ WT-1012-c ┆ … ┆ WT-1012-e ┆ WT-911-d_ ┆ Ob-DHA-d_ ┆ WT-b_S12 │
│ ---       ┆ _L007_R1_ ┆ S154_L007 ┆ _S135_L00 ┆   ┆ _S152_L00 ┆ S144_L007 ┆ S147_L007 ┆ 6_L007_R │
│ str       ┆ 001       ┆ _R1_001   ┆ 7_R1_001  ┆   ┆ 7_R1_001  ┆ _R1_001   ┆ _R1_001   ┆ 1_001    │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 10FTHF5GL ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Utl       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10FTHF5GL ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Utm       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10FTHF6GL ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Utl       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10FTHF6GL ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Utm       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10FTHF7GL ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Utl       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
combined_df = pos_df.join(neg_df, on="Reaction", how = "inner", suffix="_neg")

In [31]:
combined_df.head().collect()

shape: (5, 81)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Reaction  ┆ WT-d_S141 ┆ Ob-DHA-e_ ┆ WT-1012-c ┆ … ┆ WT-1012-e ┆ WT-911-d_ ┆ Ob-DHA-d_ ┆ WT-b_S12 │
│ ---       ┆ _L007_R1_ ┆ S154_L007 ┆ _S135_L00 ┆   ┆ _S152_L00 ┆ S144_L007 ┆ S147_L007 ┆ 6_L007_R │
│ str       ┆ 001       ┆ _R1_001   ┆ 7_R1_001  ┆   ┆ 7_R1_001_ ┆ _R1_001_n ┆ _R1_001_n ┆ 1_001_ne │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ neg       ┆ eg        ┆ eg        ┆ g        │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 10FTHFtl  ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 10FTHFtm  ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 11DOCRTSL ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ tm        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11DOCRTSL ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ tr        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11DOCRTST ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ RNtm      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [43]:
sample = "Ob-DHA-e_S154_L007_R1_001"
combined_df.select(pl.col(sample).eq(pl.col(sample + "_neg")).alias("equal_pn").all()).collect()

shape: (1, 1)
┌──────────┐
│ equal_pn │
│ ---      │
│ bool     │
╞══════════╡
│ true     │
└──────────┘

Ok, so yeah the pos and neg are always equal to each other.

In [5]:
df_py = pl.scan_csv("penalties_py_0.txt", separator="\t")

In [9]:
df_rs = pl.scan_csv("crates/penalties.csv")
df_rs_pos = df_rs.select(pl.col("_reaction_name").alias("Reaction") + "_pos", pl.selectors.numeric())
df_rs_neg = df_rs.select(pl.col("_reaction_name").alias("Reaction") + "_neg", pl.selectors.numeric())
df_rs = df_rs_pos.collect().extend(df_rs_neg.collect()).lazy()

In [14]:
sample = "Ob-DHA-e_S154_L007_R1_001"
df_py.join(df_rs, on="Reaction", how="inner", suffix="_rs").filter(~pl.col(sample).eq(pl.col(sample + "_rs")).alias("not equal")).select(pl.col("Reaction"), pl.col(sample), pl.col(sample + "_rs")).collect()

shape: (126, 3)
┌───────────────────────┬───────────────────────────┬──────────────────────────────┐
│ Reaction              ┆ Ob-DHA-e_S154_L007_R1_001 ┆ Ob-DHA-e_S154_L007_R1_001_rs │
│ ---                   ┆ ---                       ┆ ---                          │
│ str                   ┆ f64                       ┆ f64                          │
╞═══════════════════════╪═══════════════════════════╪══════════════════════════════╡
│ 5ADTSTSTERONESULT_pos ┆ 1.0                       ┆ 0.158996                     │
│ ACACT1r_pos           ┆ 0.134755                  ┆ 0.10781                      │
│ ACACT1x_pos           ┆ 0.134755                  ┆ 0.10781                      │
│ ADMDC_pos             ┆ 0.595922                  ┆ 0.207176                     │
│ AMY1e_pos             ┆ 0.109185                  ┆ 0.109167                     │
│ …                     ┆ …                         ┆ …                            │
│ RE1796R_neg           ┆ 0.619759                  ┆ 0.128082                     │
│ RE3111M_neg           ┆ 0.619759                  ┆ 0.128082                     │
│ RE3111R_neg           ┆ 0.619759                  ┆ 0.128082                     │
│ RE3308R_neg           ┆ 0.075203                  ┆ 0.072355                     │
│ RE3310R_neg           ┆ 0.075203                  ┆ 0.072355                     │
└───────────────────────┴───────────────────────────┴──────────────────────────────┘

In [13]:
df_rs = pl.scan_csv("crates/penalties_iso.csv")
df_rs_pos = df_rs.select(pl.col("_reaction_name").alias("Reaction") + "_pos", pl.selectors.numeric())
df_rs_neg = df_rs.select(pl.col("_reaction_name").alias("Reaction") + "_neg", pl.selectors.numeric())
df_rs = df_rs_pos.collect().extend(df_rs_neg.collect()).lazy()
sample = "Ob-DHA-e_S154_L007_R1_001"
df_py.join(df_rs, on="Reaction", how="inner", suffix="_rs").filter(~pl.col(sample).eq(pl.col(sample + "_rs")).alias("not equal")).select(pl.col("Reaction"), pl.col(sample), pl.col(sample + "_rs")).collect()

shape: (126, 3)
┌───────────────────────┬───────────────────────────┬──────────────────────────────┐
│ Reaction              ┆ Ob-DHA-e_S154_L007_R1_001 ┆ Ob-DHA-e_S154_L007_R1_001_rs │
│ ---                   ┆ ---                       ┆ ---                          │
│ str                   ┆ f64                       ┆ f64                          │
╞═══════════════════════╪═══════════════════════════╪══════════════════════════════╡
│ 5ADTSTSTERONESULT_pos ┆ 1.0                       ┆ 0.158996                     │
│ ACACT1r_pos           ┆ 0.134755                  ┆ 0.10781                      │
│ ACACT1x_pos           ┆ 0.134755                  ┆ 0.10781                      │
│ ADMDC_pos             ┆ 0.595922                  ┆ 0.207176                     │
│ AMY1e_pos             ┆ 0.109185                  ┆ 0.109167                     │
│ …                     ┆ …                         ┆ …                            │
│ RE1796R_neg           ┆ 0.619759                  ┆ 0.128082                     │
│ RE3111M_neg           ┆ 0.619759                  ┆ 0.128082                     │
│ RE3111R_neg           ┆ 0.619759                  ┆ 0.128082                     │
│ RE3308R_neg           ┆ 0.075203                  ┆ 0.072355                     │
│ RE3310R_neg           ┆ 0.075203                  ┆ 0.072355                     │
└───────────────────────┴───────────────────────────┴──────────────────────────────┘

So the isoform summing change is still not quite identical. But 500 reactions differ -> 126